### ISSUE TITLE
suboptimal req filling

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#185]
"Hi,
I noticed that I have a class that is both a HASS-H and HASS-A, and I have another HASS-H (not another HASS-A), but I am not getting the HASS-A requirement. It seems that it is not prioritizing the type to be what is most efficient."

**Comment by npfoss** [comment]
Actual problem: attributes missing in FireRoad

**Comment by venkatesh-sivaraman** [comment]
The dev server now shows multiple HASS requirements when available (for example, 21L.013, 24.912). The `hass_attribute` key will look like `HASS-H,HASS-A` in these cases. Let me know once you have a parser that can deal with these attributes, and I'll send the changes to prod.

**Comment by georgiashay** [comment]
Multiple hass attributes should be handled on our end now.  Does the progress endpoint also work with those classes?

**Comment by npfoss** [comment]
We can handle comma-separated HASS attributes now, but I think it's still a problem with the audit engine because we're just not getting credit for 21L.013 as a HASS A or H:
![image](https://user-images.githubusercontent.com/10506482/57209896-6cad5b00-6fa8-11e9-8ea1-2ea0d9066f8d.png)

**Comment by georgiashay** [comment]
Should just be like a one line change on the progress endpoint then. 

Also want to note that the progress endpoint doesn't handle classes not being allowed to double-dip requirements, so the issue here isn't really suboptimal req filling since it doesn't check which one to fill at all.  Once it is resolved, both HASS-A and HASS-H should show as fulfilled.  I'm not sure if that is technically allowed, so this is probably something we should document somewhere unless we feel it's sufficiently covered by all the warnings telling you to check the official audit.

**Comment by npfoss** [comment]
I think the best solution here is to overcount, because once we get around to restricting double counting we'll need it to say that it can fulfill either. I'd say go ahead and PR the change, and see if Venkat agrees.

**Comment by venkatesh-sivaraman** [comment]
This should be fixed now

**Comment by georgiashay** [comment]
Fixed, closing
