### ISSUE TITLE
Lots of errors if there are no roads

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#197]
Lots of console errors if you have no roads on login and it doesn't let you dismiss the messages.

**Comment by ttpcodes** [comment]
Additional things related to this issue:
- Some people that I know who have been using `courseroad2` have been logging in for the first time only to see no roads, causing this issue.
- Having no roads breaks a lot of things, as in, not even functionality for searching for classes works.

**Comment by georgiashay** [comment]
Do the errors still occur if you have roads and delete them, or is it only on first login? And do the errors happen only when you first create an account, or with anyone that has no roads?

**Comment by npfoss** [comment]
Recent issue reported by user (see email) and solution (thanks Michael):
> "When some users log in, they have no initial road, which causes Courseroad to act up and prevent access to most functionality until they manually create the road."

**Comment by npfoss** [comment]
Moving to p1 partially because this should be a quick fix

**Comment by ttpcodes** [comment]
My thinking is that chances are people will run into the issue of there being no roads if they log in and there aren't any initial roads or if they delete their final remaining road. Instead of enforcing that a user always has a minimum of one road in existence, I think that we should handle the case of there being no roads and from there, do something along the lines of displaying a message that says "You don't have any roads! Click + to create one!" What do you think?

**Comment by georgiashay** [comment]
Does the error occur both if you have deleted all roads and if you have never created one?

**Comment by ttpcodes** [comment]
So, if you delete all roads, you just end up with a blank area where a `Road` is supposed to be displayed (not even `Semester` labels). You can still search for classes, but you obviously won't be able to do anything until you add a `Road` back in. If you refresh the page and still have no roads, you'll run into the same issues as if you never had created a `Road`.

**Comment by georgiashay** [comment]
Still errors :(

**Comment by georgiashay** [comment]
Fixed
