### ISSUE TITLE
Improve cookie banner UX

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [sipb/courseroad2#213]
Going off of #210, I've also heard some people saying things weren't saved when they opened the site again, and I think it's probably a UX issue. Not an expert on GDPR or the "Cookie Law", but after reading a bit about it I have some suggestions that might improve the cookie banner: 

1. Use "implied consent" - something like "By using CourseRoad you accept our use of cookies". I thought this sounded sketchy at first, but amazon.es does it, so it's probably legit?
2. Make the banner very prominent, closer to the top, and in a different color. If it's not styled to imply _ACTION REQUIRED,_ people are going to expect the site to work whether or not they dismiss it.

Either way, it's pretty important to make sure this banner/alert is super clear, because it has the potential to nullify a lot of the good UX going on downstream.

**Comment by georgiashay** [comment]
Hmm, I'm not sure if we can put it at the top without getting in the way of other things, but I guess that's your point - we want them to accept it right away, or there will be unexpected behavior.  It's _technically usable_ without accepting cookies if you really wanted to, you'd just have to download and upload your roads and never log in, but that should be a tiny minority of users if any.

For the implied consent thing, would we just start using cookies right away, even before they have pressed OK/dismissed the message?  This would prevent unsaved roads but I'm also not sure about if this is okay.  I have seen that language on other websites, but I'm not sure if they use cookies before you dismiss it?

**Comment by venkatesh-sivaraman** [comment]
According to [this website](https://www.privacypolicies.com/blog/eu-cookie-law/#option-3-get-implied-consent), you can use a time window beyond which consent is assumed if the user is still on the site. You could also see if the user interacts with elements on the page; e.g. if they login or start building their road you assume they've consented.

I do think the banners should be a different color, even if they're at the bottom - the white on white makes them really hard to see on a big screen.

**Comment by georgiashay** [comment]
Don't necessarily like these colors, but is something like this (nothing different, just colored) sufficient for the UI part of this? (And if so, what color is best that doesn't clash with the rest of the UI?)

![image](https://user-images.githubusercontent.com/33201801/56784548-fd24b800-67be-11e9-9106-a4a62f614283.png)

**Comment by npfoss** [comment]
I am in very strong support of fixing this asap, I've heard reports of people losing their stuff because of this.

Maybe try the orange and yellow from the loading bars for the cookies and oldcourseroad respectively, @georgiashay ?

**Comment by georgiashay** [comment]
![image](https://user-images.githubusercontent.com/33201801/56839705-ccda2980-6851-11e9-9e8a-61ec9f5bb21f.png)

**Comment by georgiashay** [comment]
I think I like the lime better, tbh

**Comment by venkatesh-sivaraman** [comment]
Yellow/green for springtime :P 

Are you also planning to do the "implied consent" thing? The phrase still sounds really wrong in this day and age, but I think it's for the user's own good...

**Comment by georgiashay** [comment]
Yeah, I think I still want to have the explicit opt-in as well though, so I'm still working out the wording and then I'll set it up to allow cookies on first interaction/on a timer.

**Comment by ttpcodes** [comment]
Something that someone recommended to me was that we make the working about cookies a bit more explicit (as in, these features that may be seen as important **will not work** unless we have the ability to store cookies). Additionally, someone mentioned that it would be nice for the page to do what some websites like `Gmail` do, which is to create a popup if the road hasn't saved, asking the user to be sure that they want to leave and dump their changes. What do you think?

**Comment by georgiashay** [comment]
+1 to the popup

**Comment by venkatesh-sivaraman** [comment]
Those are both good suggestions. Just to reiterate, if you're going to require an explicit opt-in I think you're going to  _have_ to make it an alert that prevents the user from interacting with the rest of the site. But people hate alerts and clicking on banners about cookies, which is why I think just starting to use cookies would be better for the user. The hybrid idea of asking for consent while implicitly using cookies could work well, provided you also have an opt-out button on the banner. Something like "CourseRoad uses cookies to remember your login information and save your roads," with buttons saying "I accept" and "Opt out", maybe?

**Comment by georgiashay** [comment]
I just implemented something but I'm not sure if it's safe enough cookie-law-wise.  I have the banner at the bottom with the I accept and Opt out buttons (as well as language stating if you continue to use the website it is also accepting cookies), and have it so that as soon as you make a change to a road it is taken as consent to cookies.  I'm worried that this is bad because the banner just silently disappears, and it seems like there should be some way to either go back and opt out, or at least see what you consented to implicitly.  Any ideas?

**Comment by georgiashay** [comment]
![image](https://user-images.githubusercontent.com/33201801/56844174-15a5d880-687a-11e9-8b5d-69df06e3411d.png)

**Comment by georgiashay** [comment]
Another idea is to keep the banner up until they explicitly choose one, but somehow indicate if they've already implicitly chosen one.

**Comment by npfoss** [comment]
I think it defaulting to using cookies is a must because so many people are loosing stuff and that's way worse than complying with a law for the EU directed mainly at corporations and sites with millions of users to protect consumers from the profit-driven incentives against respecting their privacy. CourseRoad is simply not the use case that anyone is worried about. I think defaulting to yes and presenting those two options is the most we should do.

Another concern is the wording because technically it will still work incognito. So maybe just leave it as "important features".

In response to the accidental reload and never see it again issue, we could just put a 5 second timer or something before actually turning on cookies.

This way also means we don't have to do an annoying popup.

And I think the yellow and lime you've chosen are good.

**Comment by georgiashay** [comment]
I think I'm going to have it so that as soon as you edit a road it sets cookies to true, but leaves the banner up.  Working out some weird issues with emitting to and from children (that will hopefully go away with vuex integration), but this seems like the best compromise?

As long as we turn on cookies when they edit a road, we shouldn't need to bother with a timer.

I can remove the "like saving roads" but I did want to emphasize why you should choose to accept cookies without the user having to figure that out on their own by losing a road.
