### ISSUE TITLE
Can't drag 6.041A from the audit (only on courseroad.mit.edu)

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#214]
Not sure if a fresh push to prod will fix this, but I am unable to drag 6.041 in the 6-2 requirements list on to my road, but other subjects near it like 6.008 drag fine.  Weirdly, not seeing this issue on localhost.

**Comment by npfoss** [comment]
I suspect 6.041A may not exist in the catalog returned by FireRoad. Haven't tested this thoroughly but it showed up when I was testing importing roads too

**Comment by venkatesh-sivaraman** [comment]
Something changed in the fall catalog that broke the parser for 6.041, I'm looking into it now

**Comment by venkatesh-sivaraman** [comment]
Well, it's straight up not on the registrar site now. Apparently they're revamping it to be a single 12-unit course, but in the meantime there's no 6.041 in the catalog. :(

This gets at one of the issues I've been thinking about, which is that what shows on the registrar site is very tied to the upcoming semester. Right now the FireRoad server stores all previous parsed catalogs and looks for the most recent semester to populate the database, but it might be possible to synthesize them together and add a `last-semester-offered` key to each course so that the backend can return the most up-to-date version of each individual course. This would essentially allow us to show subjects that have been discontinued since FireRoad was released, which approaches the behavior of old CourseRoad without using the Data Warehouse.

**Comment by georgiashay** [comment]
I like the last semester offered idea.  It is going to be frustrating for users if they want to add classes that existed in the past but not this semester.

**Comment by venkatesh-sivaraman** [comment]
OK, the dev server should now provide you with an `is_historical` JSON key indicating whether the subject is no longer offered in the current semester. If `is_historical` is True, there will also be a `source_semester` key that gives a value like `fall-2018` indicating when the subject was last offered. Starting tomorrow, the prod server will also provide these values. And when I next update the mobile apps, they'll show a warning in the course details view indicating that the course is no longer offered.

**Comment by georgiashay** [comment]
Awesome!  We will just have to add tests & warnings with the new information.

**Comment by npfoss** [comment]
Yeah that sounds great, thanks!

Can you push that improvement to the production server too please @venkatesh-sivaraman? The main site still doesn't show any `/6.041[AB]?/` which will definitely interfere with importing roads, and I'm sure there are tons of special subject with the same problem.

**Comment by venkatesh-sivaraman** [comment]
Yep, it's going to go out in the next database refresh, which happens in the early morning :)

**Comment by npfoss** [comment]
Awesome, thank you!

**Comment by npfoss** [comment]
Is 4.610 not having a title this kind of problem or is that something else? I'm not sure how historical it is or anything
