### ISSUE TITLE
Initial loading performance analysis

### ISSUE THREAD

**Issue by venkatesh-sivaraman** [sipb/courseroad2#219]
Opening the page can be really slow, especially when you have a lot of roads - it actually hangs Safari sometimes. Just for the sake of thoroughness, here's my network usage, sorted by API call duration:

![Screen Shot 2019-04-26 at 5 58 48 PM](https://user-images.githubusercontent.com/13065028/56838748-3ad02200-684d-11e9-81dd-bd7d6f184b49.png)

Some observations:

1. It looks like calls to `verify` are queuing up and taking a long time, that should only get called once per page load.
2. There's a nearly **10-second** gap between when you first retrieve the roads with `/sync/roads?id=XXX` and the next API call. I also saw you're retrieving the full descriptions of all courses in the catalog. What's going on in there, and does it have to take place before the user can see their roads?
3. It seems like you're gearing up to display all of the user's roads whenever they open or reload the page. Why not just sync the one that you know is going to be open?
4. If the user is going to have to wait a couple seconds before they can interact with the page, you could probably dim the page and have a loading bar that shows what it's doing and how long it's going to take. More of a psychological thing than a bug fix, but could be surprisingly effective.

(FWIW, I know the requirements progress API has been somewhat of a bottleneck - I just made some database optimizations that should give a 2-3x performance improvement.)

**Comment by npfoss** [comment]
This is super helpful, thank you for doing this analysis. I totally agree with those recommendations.

**Comment by georgiashay** [comment]
Thanks for the suggestions!

We were waiting until we implement vuex to fix this, but maybe we should go ahead and fix this before then?

For verify, I was under the impression that it should be called before any API call to check if the user is still logged in?  Is it fine to just check for errors on the API call itself, and if so, what error will be returned if the user's tokens have expired (and how can I simulate expired tokens to better test this?).

I think we do still want to load all roads at the beginning, but definitely loading the active road first and loading the rest in the background afterwards would be a good idea.  

I'm not sure what's going on with the 10-second delay, so that's going to be a priority to look into, but I'm pretty sure the catalog doesn't have to load before the roads (and if we have it set up differently and I have forgotten, we'll definitely change that).

And thanks a bunch for the database optimizations, as soon as we sort things out on our end it should be super fast now!

**Comment by venkatesh-sivaraman** [comment]
I'm not saying this is critical, just putting everything here so it gets addressed at some point :) Yeah `verify` is more of a place to prompt the user to log in at the beginning of a session, so you don't need to call it after the first time. If the user is no longer logged in you'll get a 403 error (permission denied), so you could use that to check login status during a session. Tokens expire in about a week, but I can generate a pre-expired token for you to test - I'll just email you one for dev now since an expired token doesn't expire, lol.

**Comment by georgiashay** [comment]
Definitely deserves the P1 label, it's super annoying every time you log in and we're probably sending 2-5+ times the # of API calls that are actually needed.

The token will be super helpful, thanks!
