### ISSUE TITLE
Vuetify briefly broken?

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#222]
![image](https://user-images.githubusercontent.com/33201801/56844341-e8a6f500-687c-11e9-91cf-aa49696fb701.png)

Seemed to occur on slow internet connection... is this just due to development or could users see this potentially?

**Comment by npfoss** [comment]
Was this before or after Michael's PR which bundled everything with the build?

If it was after, maybe it means we need to change the order of our imports or something? Or reduce package size?

**Comment by ttpcodes** [comment]
I used Firefox's debugging tools to simulate a 2G connection, and it seems that even in such a circumstance, the page should still be able to load the fonts and styles relatively quickly. It makes sense though that this issue would occur after my PR though, because the CSS is now separate from the JS, meaning that if the JS has loaded before the CSS, there might potentially be some style issues. The only way we can really speed up loading of assets though, is to shrink down our asset files.

@georgiashay Do you have more information on how you triggered this?

**Comment by georgiashay** [comment]
It was last night so it would have had to be after a Michael's PR.  It actually looks like just the material icons hadn't loaded yet, not all of vuetify, but I have no idea how those are loaded.  Regardless, I think it eventually loaded and looked right so it's probably not a huge deal even if it happens again.

**Comment by ttpcodes** [comment]
The icons themselves are part of multiple font files which we're now serving on our end instead of retrieving from some other `CDN`.  It's slightly slower, but alleviates the concern of the `CDN` going down and things being inaccessible.

**Comment by georgiashay** [comment]
I'm not positive if this happened for me before or after your CDN PR.  Based on that information, probably before - so this isn't something to worry about.
