### ISSUE TITLE
petitions -- UI

### ISSUE THREAD

**Issue by npfoss** [sipb/courseroad2#279]
This is the issue for discussing the user workflow to add a petition.

Some ideas off the top of my head (which could all use improvement):
- There could be a dropdown and button in the 'info' dialog that comes up when you click the little `i` next to a req. The dropdown has all your subjects, and you can choose one and then click "override and count" to enter the petition.
- You could drag a subject from your road into the req you want to override.
- There could be a `+ override/petition` button at the bottom of every list of requirements (in the audit) that brings up a dialog to choose which one.

Thoughts?

**Comment by georgiashay** [comment]
1. This is probably the most intuitive option that doesn't add any clutter to the page.  It is a lot of clicks though, and searching through the dropdown might not be the best workflow when there are a lot of classes.

2. I like this idea because there's few clicks to make it happen, but I'm not sure how to make it clear that this can be done.  Would probably need to be paired with one of the others.

3. I like that it's very visible but it also could take up some space depending on how it's implemented.  Would it be at the end of every sub-list or just the main category?  


Some other (not well thought out) ideas:
* Dragging the req onto a subject in the road to "apply" the requirement to it; essentially the same as above but you are dragging a small thing onto a big thing.
* Petition a class to count for a requirement from within the class info card 
* Add it to a context menu on the classes in the road.  Not a huge fan of this idea but there are also markings (P/NR, Exploratory, Easy, Difficult, etc...) that fireroad has in this context menu that we don't have anywhere and it might become hard to fit everything in without them.
* Click on the i to open the info dialog but then you somehow drag the class in to count as a petition

**Comment by npfoss** [comment]
1. Yeah sorry not a dropdown, probably one of those search things like the one for choosing majors, or something simpler that still lets you type. I think this is still my favorite option.

As for context menus, I personally don't like right clicking but I'm not sure why or how representative that is of normal people... It's probably the last thing I would try though, if I even thought to try it.

Also, I agree with the general drive to minimize clicks. This action might be uncommon enough that it's worth sacrificing that slightly for the aesthetic/clutter though. For example I just had to explain what a petition was to my bio friend who's a senior, and I personally depend on a decent number of petitions would only use it once or twice a semester.

**Comment by venkatesh-sivaraman** [comment]
These ideas all sound reasonable. I’m thinking about how to implement this feature in FireRoad as well, and I think the requirements interface is already fairly interaction-dense (you guys may feel the same about your tree UI). For this reason I like the 3rd option the best, as it is (1) the most discoverable and (2) allows us the most flexibility for how a petition should be created without cluttering up the UI further.

Here’s a mock-up for what I’m imagining the FireRoad flow to look like- I prefer to call them “overrides” to make it clear that this isn’t official, but you get the idea:

![9502C823-7016-44CA-84B5-6C4EC7FB1FB7](https://user-images.githubusercontent.com/13065028/63217255-3a131280-c100-11e9-8ed2-b7531bc74f69.jpeg)

This would allow you to select one or more courses from your road to override any requirement, then display those courses where the old requirement used to be with a highlighted background. That way, if you remove one of those courses from your road, it will be clear that the override would no longer be valid. (You would also be able to simply override without a course, indicated by the “No Course” option.) Thoughts?

**Comment by venkatesh-sivaraman** [comment]
re. context menus, I would also argue against a right-click menu because people usually expect a right-click to bring up the browser’s context menu (except in rare exceptions like Google Drive). However, since you guys are running on devices with mice/trackpads, you have an advantage that the mobile app doesn’t have: hovering. You could make a hover menu over the courses that include any of the features you aren’t able to show immediately, or that are currently not very discoverable. Just a thought.

**Comment by georgiashay** [comment]
I support this reasoning for using option 3 for UI.  In courseroad we could have the same Create an Override button and it would lead to a popup with the same options to choose a requirement to override and courses to override it with.

**Comment by CyanoKobalamyne** [comment]
This has just been rolled out in #404, and I realized that petitions are for specific subjects. (But if that's not the case, and I missed something, let me know.) However, I believe that most departments grant petitions to use a subject to fulfill a given *requirement*, which is similar to "substituting" a subject, but not quite the same thing.

E.g. 7.03 is a required subject for Course 7, so substituting a different subject here will work, but the Advanced Undergraduate Subject (AUS2) requirement of Course 6 covers a set of subjects, so if you petition a subject to count as AUS2, you are not petitioning to substitute it for a specific subject, but for the requirement in general. Of course, you could choose a subject from the list at random and add a petition for it, but that solution seems suboptimal.
